- addons/sourcemod/scripting/freak_fortress_2.sp
How did I forget when I knew that it was going to be like this.
> Fixed health being short by one player

- addons/sourcemod/data/freak_fortress_2/weapons.cfg
- addons/sourcemod/scripting/freak_fortress_2.sp
- addons/sourcemod/scripting/include/rtd.inc
> The Self-Knockback Update Thing

- addons/sourcemod/scripting/freak_fortress_2.sp
> Forgot I changed this

- README.md
- addons/sourcemod/scripting/freak_fortress_2.sp
> The Boss Name Server Name Update

- README.md
- addons/sourcemod/scripting/freak_fortress_2.sp
> Fixed owner bosses

- addons/sourcemod/scripting/freak_fortress_2.sp
No more turn on the cvar for only few bosses yay.
Also commented out ignite sound cause errors.
> Self-Knockback Setting for Bosses

- addons/sourcemod/scripting/freak_fortress_2.sp
> No first round setting and keep boss setting

- README.md
- README.txt
- addons/sourcemod/scripting/freak_fortress_2.sp
> The Server Optional Boss Menu Update

- README.md
- README.txt
- addons/sourcemod/scripting/freak_fortress_2.sp
> The Queue Point Setting Update

- addons/sourcemod/scripting/freak_fortress_2.sp
- addons/sourcemod/translations/freak_fortress_2_prefs.phrases.txt
That took longer than it should.
> Advanced Music System

- addons/sourcemod/scripting/freak_fortress_2.sp
> Skip & Shuffle Update

- .travis.yml
- addons/sourcemod/scripting/freak_fortress_2.sp
> The Moar Companion  Stuff Update

- addons/sourcemod/scripting/freak_fortress_2.sp
> Stuff Stuff Update

- addons/sourcemod/scripting/freak_fortress_2.sp
Just updated and deleted some lines. I don't know how to improve the loop algorithm for Command_GetHP and MessageTimer for better translation behavior.
> Additional improvement for translations

- .travis.yml
- addons/sourcemod/scripting/freak_fortress_2.sp
- addons/sourcemod/scripting/include/freak_fortress_2.inc
- addons/sourcemod/translations/freak_fortress_2.phrases.txt
> Moar Stuff Update

- README.md
- addons/sourcemod/scripting/freak_fortress_2.sp
- addons/sourcemod/scripting/include/freak_fortress_2.inc
> Even Moar Stuff Update

- README.md
- README.txt
- addons/sourcemod/scripting/freak_fortress_2.sp
- addons/sourcemod/translations/freak_fortress_2.phrases.txt
> HUDs, Shields, and Rename

- .travis.yml
- README.md
- addons/sourcemod/scripting/freak_fortress_2.sp
- addons/sourcemod/scripting/include/freak_fortress_2.inc
- addons/sourcemod/translations/freak_fortress_2.phrases.txt
> The HUD Update

- addons/sourcemod/scripting/freak_fortress_2.sp
- addons/sourcemod/scripting/freaks/ffbat_defaults.sp
- addons/sourcemod/scripting/include/freak_fortress_2.inc
- addons/sourcemod/translations/freak_fortress_2.phrases.txt
- addons/sourcemod/translations/freak_fortress_2_prefs.phrases.txt
- Added ff2hud command to disable/enable certain HUD elements
- Removed boss info timer because it was a bit useless
- Added FF2_OnMusic2 for name/artist of songs
- Fixed `sound_stalemate` only for rival bosses
- Updated to current updates towards Official 1.11 Beta
- HUD is hidden during the killcam
- Glows on clients can now decay
- Subplugin now fully supports new named args
- Fixed some delay args in the subplugin at 0.0 still having a minor delay
> [Update] 1.19.2

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.md
- CONTRIBUTING.md
- README.md
- README.txt
- addons/sourcemod/configs/adminmenu_ff2.cfg
- addons/sourcemod/scripting/freak_fortress_2.sp
- addons/sourcemod/scripting/freaks/ffbat_defaults.sp
- addons/sourcemod/scripting/include/freak_fortress_2.inc
- addons/sourcemod/scripting/include/freak_fortress_2_subplugin.inc
- addons/sourcemod/scripting/include/freak_fortress_2_vsh_feedback.inc
- addons/sourcemod/translations/freak_fortress_2_prefs.phrases.txt
- index.html
- style.css
> [Update] 1.19.5

- .travis.yml
- addons/sourcemod/data/freak_fortress_2/difficulty.cfg
- addons/sourcemod/data/freak_fortress_2/weapons.cfg
- addons/sourcemod/scripting/freak_fortress_2.sp
- addons/sourcemod/scripting/freaks/ffbat_defaults.sp
- addons/sourcemod/scripting/include/freak_fortress_2.inc
- addons/sourcemod/scripting/include/freak_fortress_2_stocks.inc
- addons/sourcemod/translations/freak_fortress_2_prefs.phrases.txt
- index.html
- style.css
Fixes #72 
Fixes #83 
Fixes #89 
Fixes #107 
Fixes #108 
Fixes #110 
Fixes #111
> [Update] 1.19.6

- addons/sourcemod/scripting/freak_fortress_2.sp
Use ff2_enable_sandmanstun to enable the stun ability for sandman. #124
> Add a cvar to enbale the stun ability for the sandman.

- addons/sourcemod/scripting/freak_fortress_2.sp
- addons/sourcemod/scripting/freaks/ffbat_defaults.sp
Stupid piece of code that had no reason to be ever added in the first place; NecGaming runs FF2 with this modification and faces no issues with animations.
> Broken 1st person animations

- addons/sourcemod/scripting/freak_fortress_2.sp
Mistaking Clear() by Cleanup() caused [this problem](https://forums.alliedmods.net/showpost.php?p=2713922&postcount=107). I have no idea how did i miss that.
> Fix memory leak

- addons/sourcemod/scripting/freak_fortress_2.sp
currently only check if the first ability's sub plugin is available
should check to see if all ability's sub plugin is available
> check to see if all ability's sub plugin is available

- addons/sourcemod/scripting/freak_fortress_2.sp
- addons/sourcemod/scripting/include/freak_fortress_2.inc
Thanks to @MAGNAT2645  for the debugs #139
> Fix leak, crash and empty cache

- addons/sourcemod/scripting/freak_fortress_2.sp
Caused https://forums.alliedmods.net/showthread.php?t=330237
> Update key lookup and start caching HasAbility

- addons/sourcemod/scripting/freak_fortress_2.sp
- addons/sourcemod/scripting/include/freak_fortress_2.inc
Hopefully last one, will remove the debugs once I'm sure it wont produce any bug again
> Yet another bug fix

- addons/sourcemod/scripting/freak_fortress_2.sp
> Correct an include directory
